language: python
python:
  - "3.6"
before_install:
  - pip install numpy scipy
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - cd btr/tests/
  - nose2 test_commandline